[package]
name = "pointerpos"
version = "0.1.0"
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]
edition = "2018"

[dependencies]
breadx = { version = "2.0.0", features =  	["tokio", "async", "std"] }
tokio = { version = "1", features=["full"] }